//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tieuthiminhthuong.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Product
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Vui long nhap ten san pham")]
        [Display(Name = "Product Name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Vui long them anh")]
        [Display(Name = "Product Avatar")]
        public string Avatar { get; set; }
        [Required(ErrorMessage = "Vui long chon category")]
        [Display(Name = "Category")]
        public int CategoryId { get; set; }
        [Required(ErrorMessage = "Vui long nhap Short Description")]
        [Display(Name = "Short Description")]
        public string ShortDes { get; set; }
        [Required(ErrorMessage = "Vui long nhap Short Description")]
        [Display(Name = "Full Description")]
        public string FullDescription { get; set; }
        [Required(ErrorMessage = "Vui long nhap price")]
        [Display(Name = "Price")]
        public Nullable<double> Price { get; set; }
        [Required(ErrorMessage = "Vui long nhap price Discount")]
        [Display(Name = "Price Discount")]
        public Nullable<double> PriceDiscount { get; set; }
        [Required(ErrorMessage = "Vui long nhap Stock")]
        [Display(Name = "Stock")]
        public Nullable<int> TypeId { get; set; }
        [Required(ErrorMessage = "Vui long nhap Slug")]
        [Display(Name = "Slug")]
        public string Slug { get; set; }
        [Required(ErrorMessage = "Vui long nhap Brand")]
        [Display(Name = "Brand")]
        public Nullable<int> BrandId { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<bool> ShowOnHomePage { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<System.DateTime> CreatedOnUtc { get; set; }
        public Nullable<System.DateTime> UpdatedOnUtc { get; set; }
        [NotMapped]
        public System.Web.HttpPostedFileBase ImageUpLoad { get; set; }
    }
}
